#!/bin/bash

# Builds site for a particular version
branch="gh-pages"
repository="git@github.com:darylteo/edge-site.git"

compiledDir="_site"
srcDir="src"
environmentFile="$srcDir/_dev.yml"
configFile="$srcDir/_config.yml"

# clone gh-pages if it does not exist
if [ ! -d "gh-pages" ]
then
  git clone -b "$branch" "$repository" gh-pages;
fi

# perform jekyll compilation
mkdir $compiledDir
cp "$environmentFile" "$configFile"
jekyll "$srcDir" "$compiledDir" --no-server --no-auto > /dev/null 2>&1;

# cleanup
rm $configFile