#!/bin/bash

# Publishes gh-pages
if [ -d "gh-pages" ]
then
	echo "Changing to gh-pages directory"
	pushd gh-pages;

	echo "Pushing to gh-pages"
	git add .;
	git commit;

	if [ "$?" == 1 ]
	then
		exit 1
	fi

	git push origin gh-pages;

	echo "Done";
	popd;
fi
