#!/bin/bash

# Builds site for a particular version
branch="gh-pages"
repository="git@github.com:darylteo/edge-site.git"

compiledDir="_site"
srcDir="src"
environmentFile="$srcDir/_prod.yml"
configFile="$srcDir/_config.yml"

# clone gh-pages if it does not exist
if [ ! -d "gh-pages" ]
then
	git clone -b "$branch" "$repository" gh-pages;
fi

# perform jekyll compilation
mkdir $compiledDir
cp "$environmentFile" "$configFile"
jekyll "$srcDir" "$compiledDir" --no-server --no-auto > /dev/null 2>&1;

# Publishes gh-pages
if [ -d "gh-pages" ]
then
	echo "Changing to gh-pages directory"
	pushd gh-pages;

	echo "Pushing to gh-pages"
	git add .;
	git commit -a;

	if [ "$?" == 1 ]
	then
		exit 1
	fi

	git push origin gh-pages;

	echo "Done";
	popd;
fi

rm $configFile
