#!/bin/bash

# Builds site for a particular version
branch="gh-pages"
repository="git@github.com:darylteo/edge-site.git"

compiledDir="_site"
srcDir="src"
environmentFile="$srcDir/_dev.yml"
configFile="$srcDir/_config.yml"

# perform jekyll compilation
mkdir $compiledDir
cp "$environmentFile" "$configFile"
jekyll "$srcDir" "$compiledDir/$version" --auto --no-server &
jekyll_pid=$!

pushd $compiledDir
vertx run ../server.js
popd

# cleanup
kill $jekyll_pid
rm $configFile